[package]
name = "vola-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-vola = {path = "../tree-sitter-vola"}
thiserror.workspace = true
tree-sitter.workspace = true
ahash.workspace = true
tinyvec.workspace = true
