[workspace]
members = [
"crates/tree-sitter-vola",
"crates/vola-ast",
"crates/volac",
"examples/dry-run",
"examples/runtime-patch"
]


[workspace.dependencies]
tree-sitter = "0.20.10"
thiserror = "1.0.44"
melior = "0.9.9"
