[workspace]
members = [
"crates/vola-ast",
"crates/rvsdg",
"crates/rvsdg-viewer",
"crates/vola-common",

"examples/runtime-patch",
"examples/rvsdg-simple",
]

resolver = "2"

[workspace.dependencies]
tree-sitter = "0.20.10"
thiserror = "1.0.44"
ahash = "0.8.7"
slotmap = "1.0"
graphviz-rust = "0.6.6"
backtrace = "0.3.69"
annotate-snippets = "0.9.2"
lazy_static = "1.4.0"
smallvec = "1.11.2"
smallstr = "0.3.0"
