[package]
name = "vola-tree-sitter-parser"
version = "0.2.0"
edition = "2021"

[features]
default = []
dot = ["vola-common/dot", "graphviz-rust"]

[dependencies]
tree-sitter-vola = { git = "https://gitlab.com/tendsinmende/tree-sitter-vola.git", rev = "08e93115313ecd92f692d1920916464429b56e01" }
vola-ast = { path = "../vola-ast" }
vola-common = { path = "../vola-common" }
thiserror.workspace = true
tree-sitter.workspace = true
ahash.workspace = true
graphviz-rust = { workspace = true, optional = true }
backtrace.workspace = true
lazy_static.workspace = true
smallvec = { workspace = true, features = ["serde"] }
serde = { workspace = true, optional = true }
