[package]
name = "volac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-vola = {path = "../tree-sitter-vola"}
tree-sitter.workspace = true
thiserror.workspace = true
melior.workspace = true
