[package]
name = "vola-cli"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = {workspace = true, features = ["derive"]}
volac = {path = "../volac"}
vola-common = {path = "../vola-common"}
pretty_env_logger.workspace = true
