[package]
name = "vola-cli"
version = "0.2.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = { workspace = true, features = ["derive"] }
volac.workspace = true
vola-common.workspace = true
vola-fmt.workspace = true
pretty_env_logger.workspace = true
