#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 76
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_alge = 2,
  anon_sym_prim = 3,
  anon_sym_op = 4,
  anon_sym_field = 5,
  anon_sym_LT = 6,
  anon_sym_GT = 7,
  anon_sym_COMMA = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_COLON = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_EQ = 14,
  anon_sym_SEMI = 15,
  anon_sym_let = 16,
  anon_sym_DASH = 17,
  anon_sym_BANG = 18,
  anon_sym_SLASH = 19,
  anon_sym_STAR = 20,
  anon_sym_PLUS = 21,
  anon_sym_PERCENT = 22,
  anon_sym_PLUS_EQ = 23,
  anon_sym_DASH_EQ = 24,
  anon_sym_STAR_EQ = 25,
  anon_sym_SLASH_EQ = 26,
  anon_sym_DOT = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  anon_sym_s = 30,
  anon_sym_vec = 31,
  anon_sym_mat = 32,
  anon_sym_x = 33,
  sym_number = 34,
  sym_kw_at = 35,
  sym_kw_prim = 36,
  sym_comment = 37,
  sym_source_file = 38,
  sym__definition = 39,
  sym_alge_definition = 40,
  sym_prim_definition = 41,
  sym_op_definition = 42,
  sym_field_definition = 43,
  sym_prim_list = 44,
  sym__ident_iter = 45,
  sym_parameter_list = 46,
  sym__param_iter = 47,
  sym_typed_identifier = 48,
  sym_block = 49,
  sym__stmt = 50,
  sym_prim_expr = 51,
  sym_optree = 52,
  sym__prim_list = 53,
  sym_def_prim = 54,
  sym_let_stmt = 55,
  sym__alge_expr = 56,
  sym__sub_alge_expr = 57,
  sym_scoped_expr = 58,
  sym_unary_expr = 59,
  sym_binary_expr = 60,
  sym_assignment_stmt = 61,
  sym_assignee = 62,
  sym_call_expr = 63,
  sym__alge_list = 64,
  sym_arg_access = 65,
  sym_list = 66,
  sym__list_iter = 67,
  sym__type = 68,
  sym_scalar = 69,
  sym_vec = 70,
  sym_mat = 71,
  sym_float = 72,
  aux_sym_source_file_repeat1 = 73,
  aux_sym_block_repeat1 = 74,
  aux_sym_scoped_expr_repeat1 = 75,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_alge] = "alge",
  [anon_sym_prim] = "prim",
  [anon_sym_op] = "op",
  [anon_sym_field] = "field",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_s] = "s",
  [anon_sym_vec] = "vec",
  [anon_sym_mat] = "mat",
  [anon_sym_x] = "x",
  [sym_number] = "number",
  [sym_kw_at] = "kw_at",
  [sym_kw_prim] = "kw_prim",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_alge_definition] = "alge_definition",
  [sym_prim_definition] = "prim_definition",
  [sym_op_definition] = "op_definition",
  [sym_field_definition] = "field_definition",
  [sym_prim_list] = "prim_list",
  [sym__ident_iter] = "_ident_iter",
  [sym_parameter_list] = "parameter_list",
  [sym__param_iter] = "_param_iter",
  [sym_typed_identifier] = "typed_identifier",
  [sym_block] = "block",
  [sym__stmt] = "_stmt",
  [sym_prim_expr] = "prim_expr",
  [sym_optree] = "optree",
  [sym__prim_list] = "_prim_list",
  [sym_def_prim] = "def_prim",
  [sym_let_stmt] = "let_stmt",
  [sym__alge_expr] = "_alge_expr",
  [sym__sub_alge_expr] = "_sub_alge_expr",
  [sym_scoped_expr] = "scoped_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_assignment_stmt] = "assignment_stmt",
  [sym_assignee] = "assignee",
  [sym_call_expr] = "call_expr",
  [sym__alge_list] = "_alge_list",
  [sym_arg_access] = "arg_access",
  [sym_list] = "list",
  [sym__list_iter] = "_list_iter",
  [sym__type] = "_type",
  [sym_scalar] = "scalar",
  [sym_vec] = "vec",
  [sym_mat] = "mat",
  [sym_float] = "float",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_scoped_expr_repeat1] = "scoped_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_alge] = anon_sym_alge,
  [anon_sym_prim] = anon_sym_prim,
  [anon_sym_op] = anon_sym_op,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_vec] = anon_sym_vec,
  [anon_sym_mat] = anon_sym_mat,
  [anon_sym_x] = anon_sym_x,
  [sym_number] = sym_number,
  [sym_kw_at] = sym_kw_at,
  [sym_kw_prim] = sym_kw_prim,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_alge_definition] = sym_alge_definition,
  [sym_prim_definition] = sym_prim_definition,
  [sym_op_definition] = sym_op_definition,
  [sym_field_definition] = sym_field_definition,
  [sym_prim_list] = sym_prim_list,
  [sym__ident_iter] = sym__ident_iter,
  [sym_parameter_list] = sym_parameter_list,
  [sym__param_iter] = sym__param_iter,
  [sym_typed_identifier] = sym_typed_identifier,
  [sym_block] = sym_block,
  [sym__stmt] = sym__stmt,
  [sym_prim_expr] = sym_prim_expr,
  [sym_optree] = sym_optree,
  [sym__prim_list] = sym__prim_list,
  [sym_def_prim] = sym_def_prim,
  [sym_let_stmt] = sym_let_stmt,
  [sym__alge_expr] = sym__alge_expr,
  [sym__sub_alge_expr] = sym__sub_alge_expr,
  [sym_scoped_expr] = sym_scoped_expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_assignment_stmt] = sym_assignment_stmt,
  [sym_assignee] = sym_assignee,
  [sym_call_expr] = sym_call_expr,
  [sym__alge_list] = sym__alge_list,
  [sym_arg_access] = sym_arg_access,
  [sym_list] = sym_list,
  [sym__list_iter] = sym__list_iter,
  [sym__type] = sym__type,
  [sym_scalar] = sym_scalar,
  [sym_vec] = sym_vec,
  [sym_mat] = sym_mat,
  [sym_float] = sym_float,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_scoped_expr_repeat1] = aux_sym_scoped_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_alge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prim] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_op] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_at] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_prim] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_alge_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_prim_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_op_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_prim_list] = {
    .visible = true,
    .named = true,
  },
  [sym__ident_iter] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym__param_iter] = {
    .visible = false,
    .named = true,
  },
  [sym_typed_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_optree] = {
    .visible = true,
    .named = true,
  },
  [sym__prim_list] = {
    .visible = false,
    .named = true,
  },
  [sym_def_prim] = {
    .visible = true,
    .named = true,
  },
  [sym_let_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym__alge_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__sub_alge_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_scoped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_assignee] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__alge_list] = {
    .visible = false,
    .named = true,
  },
  [sym_arg_access] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__list_iter] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_vec] = {
    .visible = true,
    .named = true,
  },
  [sym_mat] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scoped_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '%') ADVANCE(31);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '>') ADVANCE(12);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == '[') ADVANCE(37);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(31);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '>') ADVANCE(12);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '+') ADVANCE(5);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == '[') ADVANCE(37);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '%') ADVANCE(31);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(42);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_kw_at);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == 'o') ADVANCE(6);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead == 'v') ADVANCE(9);
      if (lookahead == 'x') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 11:
      if (lookahead == 'g') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_op);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_kw_prim);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_mat);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_vec);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_alge);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_prim);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_alge] = ACTIONS(1),
    [anon_sym_prim] = ACTIONS(1),
    [anon_sym_op] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_vec] = ACTIONS(1),
    [anon_sym_mat] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_kw_at] = ACTIONS(1),
    [sym_kw_prim] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(107),
    [sym__definition] = STATE(20),
    [sym_alge_definition] = STATE(20),
    [sym_prim_definition] = STATE(20),
    [sym_op_definition] = STATE(20),
    [sym_field_definition] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_alge] = ACTIONS(5),
    [anon_sym_prim] = ACTIONS(7),
    [anon_sym_op] = ACTIONS(9),
    [anon_sym_field] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(29), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    STATE(46), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [41] = 10,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(2), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    STATE(44), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [82] = 10,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    ACTIONS(37), 1,
      sym_kw_at,
    STATE(92), 1,
      sym__alge_list,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(39), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [122] = 10,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    ACTIONS(41), 1,
      sym_kw_at,
    STATE(106), 1,
      sym__list_iter,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [162] = 10,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_kw_at,
    ACTIONS(43), 1,
      anon_sym_RPAREN,
    STATE(122), 1,
      sym__alge_list,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(39), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [202] = 10,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_kw_at,
    ACTIONS(45), 1,
      anon_sym_RPAREN,
    STATE(117), 1,
      sym__alge_list,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(39), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [242] = 9,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_kw_at,
    STATE(115), 1,
      sym__alge_list,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(39), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [279] = 9,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(41), 1,
      sym_kw_at,
    STATE(105), 1,
      sym__list_iter,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [316] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(47), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(34), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [350] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(49), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(51), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [384] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [418] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(53), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(50), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [452] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(55), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(35), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [486] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_kw_at,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(48), 9,
      sym__alge_expr,
      sym__sub_alge_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [520] = 2,
    ACTIONS(61), 1,
      anon_sym_SLASH,
    ACTIONS(59), 15,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      sym_comment,
  [541] = 2,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    ACTIONS(63), 15,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      sym_comment,
  [562] = 9,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_kw_at,
    ACTIONS(71), 1,
      sym_kw_prim,
    ACTIONS(73), 1,
      sym_comment,
    STATE(57), 1,
      sym_assignee,
    STATE(100), 1,
      sym_prim_expr,
    STATE(63), 2,
      sym_optree,
      sym_call_expr,
    STATE(23), 5,
      sym__stmt,
      sym_def_prim,
      sym_let_stmt,
      sym_assignment_stmt,
      aux_sym_block_repeat1,
  [595] = 9,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_kw_at,
    ACTIONS(71), 1,
      sym_kw_prim,
    ACTIONS(75), 1,
      sym_comment,
    STATE(57), 1,
      sym_assignee,
    STATE(123), 1,
      sym_prim_expr,
    STATE(63), 2,
      sym_optree,
      sym_call_expr,
    STATE(18), 5,
      sym__stmt,
      sym_def_prim,
      sym_let_stmt,
      sym_assignment_stmt,
      aux_sym_block_repeat1,
  [628] = 7,
    ACTIONS(5), 1,
      anon_sym_alge,
    ACTIONS(7), 1,
      anon_sym_prim,
    ACTIONS(9), 1,
      anon_sym_op,
    ACTIONS(11), 1,
      anon_sym_field,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      sym_comment,
    STATE(21), 6,
      sym__definition,
      sym_alge_definition,
      sym_prim_definition,
      sym_op_definition,
      sym_field_definition,
      aux_sym_source_file_repeat1,
  [655] = 7,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      anon_sym_alge,
    ACTIONS(86), 1,
      anon_sym_prim,
    ACTIONS(89), 1,
      anon_sym_op,
    ACTIONS(92), 1,
      anon_sym_field,
    ACTIONS(95), 1,
      sym_comment,
    STATE(21), 6,
      sym__definition,
      sym_alge_definition,
      sym_prim_definition,
      sym_op_definition,
      sym_field_definition,
      aux_sym_source_file_repeat1,
  [682] = 3,
    ACTIONS(100), 1,
      anon_sym_LPAREN,
    ACTIONS(102), 1,
      anon_sym_DOT,
    ACTIONS(98), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [701] = 7,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_let,
    ACTIONS(110), 1,
      sym_kw_at,
    ACTIONS(113), 1,
      sym_kw_prim,
    ACTIONS(116), 1,
      sym_comment,
    STATE(57), 1,
      sym_assignee,
    STATE(23), 5,
      sym__stmt,
      sym_def_prim,
      sym_let_stmt,
      sym_assignment_stmt,
      aux_sym_block_repeat1,
  [727] = 4,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_let,
    STATE(24), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    ACTIONS(121), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LBRACK,
      sym_number,
      sym_kw_at,
  [747] = 2,
    ACTIONS(126), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
    ACTIONS(128), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LBRACK,
      sym_number,
      sym_kw_at,
      sym_comment,
  [763] = 1,
    ACTIONS(130), 11,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [777] = 1,
    ACTIONS(132), 11,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [791] = 2,
    ACTIONS(136), 1,
      anon_sym_DOT,
    ACTIONS(134), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [807] = 1,
    ACTIONS(138), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [820] = 1,
    ACTIONS(140), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [833] = 1,
    ACTIONS(142), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [846] = 1,
    ACTIONS(144), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [859] = 1,
    ACTIONS(146), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [872] = 1,
    ACTIONS(148), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [885] = 2,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(150), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [900] = 1,
    ACTIONS(150), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [913] = 4,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RBRACK,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(156), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
  [929] = 4,
    ACTIONS(160), 1,
      anon_sym_s,
    ACTIONS(162), 1,
      anon_sym_vec,
    ACTIONS(164), 1,
      anon_sym_mat,
    STATE(70), 4,
      sym__type,
      sym_scalar,
      sym_vec,
      sym_mat,
  [945] = 4,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(156), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
  [961] = 1,
    ACTIONS(170), 6,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [970] = 1,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [979] = 1,
    ACTIONS(174), 6,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [988] = 5,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_GT,
    STATE(80), 1,
      sym_prim_expr,
    STATE(96), 1,
      sym__prim_list,
    STATE(63), 2,
      sym_optree,
      sym_call_expr,
  [1005] = 3,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(156), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
  [1018] = 1,
    ACTIONS(182), 6,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [1027] = 3,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(156), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
  [1040] = 1,
    ACTIONS(186), 6,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [1049] = 3,
    ACTIONS(188), 1,
      anon_sym_SEMI,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(156), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
  [1062] = 1,
    ACTIONS(190), 6,
      ts_builtin_sym_end,
      anon_sym_alge,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [1071] = 3,
    ACTIONS(192), 1,
      anon_sym_SEMI,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(156), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
  [1084] = 3,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(156), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_PERCENT,
  [1097] = 2,
    ACTIONS(198), 2,
      sym_kw_at,
      sym_comment,
    ACTIONS(196), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [1107] = 2,
    ACTIONS(202), 2,
      sym_kw_at,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [1117] = 2,
    ACTIONS(206), 2,
      sym_kw_at,
      sym_comment,
    ACTIONS(204), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [1127] = 4,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(80), 1,
      sym_prim_expr,
    STATE(118), 1,
      sym__prim_list,
    STATE(63), 2,
      sym_optree,
      sym_call_expr,
  [1141] = 3,
    ACTIONS(100), 1,
      anon_sym_LPAREN,
    ACTIONS(208), 1,
      anon_sym_LT,
    ACTIONS(210), 3,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [1153] = 1,
    ACTIONS(212), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [1161] = 1,
    ACTIONS(214), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [1169] = 1,
    ACTIONS(216), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [1177] = 1,
    ACTIONS(218), 4,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1184] = 4,
    ACTIONS(220), 1,
      sym_identifier,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      sym_typed_identifier,
    STATE(99), 1,
      sym__param_iter,
  [1197] = 2,
    ACTIONS(226), 1,
      anon_sym_COLON,
    ACTIONS(224), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1206] = 1,
    ACTIONS(210), 4,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1213] = 1,
    ACTIONS(228), 4,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1220] = 1,
    ACTIONS(230), 4,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1227] = 4,
    ACTIONS(100), 1,
      anon_sym_LPAREN,
    ACTIONS(208), 1,
      anon_sym_LT,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    ACTIONS(232), 1,
      anon_sym_DOT,
  [1240] = 3,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(111), 1,
      sym_prim_expr,
    STATE(63), 2,
      sym_optree,
      sym_call_expr,
  [1251] = 1,
    ACTIONS(234), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1257] = 1,
    ACTIONS(236), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1263] = 1,
    ACTIONS(238), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1269] = 3,
    ACTIONS(220), 1,
      sym_identifier,
    STATE(75), 1,
      sym_typed_identifier,
    STATE(113), 1,
      sym__param_iter,
  [1279] = 1,
    ACTIONS(240), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1285] = 2,
    ACTIONS(242), 1,
      sym_identifier,
    STATE(98), 1,
      sym__ident_iter,
  [1292] = 2,
    ACTIONS(220), 1,
      sym_identifier,
    STATE(112), 1,
      sym_typed_identifier,
  [1299] = 2,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
  [1306] = 2,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    STATE(87), 1,
      sym_parameter_list,
  [1313] = 2,
    ACTIONS(250), 1,
      anon_sym_EQ,
    ACTIONS(252), 1,
      anon_sym_SEMI,
  [1320] = 1,
    ACTIONS(254), 2,
      sym_identifier,
      sym_kw_at,
  [1325] = 2,
    ACTIONS(256), 1,
      anon_sym_GT,
    ACTIONS(258), 1,
      anon_sym_COMMA,
  [1332] = 2,
    ACTIONS(260), 1,
      anon_sym_GT,
    ACTIONS(262), 1,
      anon_sym_COMMA,
  [1339] = 1,
    ACTIONS(264), 2,
      sym_identifier,
      sym_kw_at,
  [1344] = 2,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
  [1351] = 2,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_block,
  [1358] = 2,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    STATE(82), 1,
      sym_parameter_list,
  [1365] = 2,
    ACTIONS(242), 1,
      sym_identifier,
    STATE(101), 1,
      sym__ident_iter,
  [1372] = 2,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_block,
  [1379] = 2,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_scoped_expr,
  [1386] = 2,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    STATE(86), 1,
      sym_parameter_list,
  [1393] = 2,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_parameter_list,
  [1400] = 2,
    ACTIONS(268), 1,
      anon_sym_LT,
    STATE(84), 1,
      sym_prim_list,
  [1407] = 1,
    ACTIONS(270), 1,
      sym_identifier,
  [1411] = 1,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
  [1415] = 1,
    ACTIONS(274), 1,
      anon_sym_LPAREN,
  [1419] = 1,
    ACTIONS(276), 1,
      sym_identifier,
  [1423] = 1,
    ACTIONS(278), 1,
      anon_sym_LBRACE,
  [1427] = 1,
    ACTIONS(280), 1,
      anon_sym_GT,
  [1431] = 1,
    ACTIONS(282), 1,
      anon_sym_x,
  [1435] = 1,
    ACTIONS(284), 1,
      anon_sym_GT,
  [1439] = 1,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [1443] = 1,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
  [1447] = 1,
    ACTIONS(290), 1,
      anon_sym_GT,
  [1451] = 1,
    ACTIONS(232), 1,
      anon_sym_DOT,
  [1455] = 1,
    ACTIONS(292), 1,
      sym_number,
  [1459] = 1,
    ACTIONS(294), 1,
      sym_number,
  [1463] = 1,
    ACTIONS(296), 1,
      anon_sym_RBRACK,
  [1467] = 1,
    ACTIONS(298), 1,
      anon_sym_RBRACK,
  [1471] = 1,
    ACTIONS(300), 1,
      ts_builtin_sym_end,
  [1475] = 1,
    ACTIONS(302), 1,
      sym_identifier,
  [1479] = 1,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
  [1483] = 1,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
  [1487] = 1,
    ACTIONS(308), 1,
      anon_sym_SEMI,
  [1491] = 1,
    ACTIONS(310), 1,
      anon_sym_EQ,
  [1495] = 1,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
  [1499] = 1,
    ACTIONS(314), 1,
      sym_identifier,
  [1503] = 1,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
  [1507] = 1,
    ACTIONS(318), 1,
      sym_number,
  [1511] = 1,
    ACTIONS(43), 1,
      anon_sym_RPAREN,
  [1515] = 1,
    ACTIONS(320), 1,
      anon_sym_GT,
  [1519] = 1,
    ACTIONS(322), 1,
      sym_identifier,
  [1523] = 1,
    ACTIONS(324), 1,
      sym_number,
  [1527] = 1,
    ACTIONS(326), 1,
      anon_sym_LPAREN,
  [1531] = 1,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
  [1535] = 1,
    ACTIONS(330), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 122,
  [SMALL_STATE(6)] = 162,
  [SMALL_STATE(7)] = 202,
  [SMALL_STATE(8)] = 242,
  [SMALL_STATE(9)] = 279,
  [SMALL_STATE(10)] = 316,
  [SMALL_STATE(11)] = 350,
  [SMALL_STATE(12)] = 384,
  [SMALL_STATE(13)] = 418,
  [SMALL_STATE(14)] = 452,
  [SMALL_STATE(15)] = 486,
  [SMALL_STATE(16)] = 520,
  [SMALL_STATE(17)] = 541,
  [SMALL_STATE(18)] = 562,
  [SMALL_STATE(19)] = 595,
  [SMALL_STATE(20)] = 628,
  [SMALL_STATE(21)] = 655,
  [SMALL_STATE(22)] = 682,
  [SMALL_STATE(23)] = 701,
  [SMALL_STATE(24)] = 727,
  [SMALL_STATE(25)] = 747,
  [SMALL_STATE(26)] = 763,
  [SMALL_STATE(27)] = 777,
  [SMALL_STATE(28)] = 791,
  [SMALL_STATE(29)] = 807,
  [SMALL_STATE(30)] = 820,
  [SMALL_STATE(31)] = 833,
  [SMALL_STATE(32)] = 846,
  [SMALL_STATE(33)] = 859,
  [SMALL_STATE(34)] = 872,
  [SMALL_STATE(35)] = 885,
  [SMALL_STATE(36)] = 900,
  [SMALL_STATE(37)] = 913,
  [SMALL_STATE(38)] = 929,
  [SMALL_STATE(39)] = 945,
  [SMALL_STATE(40)] = 961,
  [SMALL_STATE(41)] = 970,
  [SMALL_STATE(42)] = 979,
  [SMALL_STATE(43)] = 988,
  [SMALL_STATE(44)] = 1005,
  [SMALL_STATE(45)] = 1018,
  [SMALL_STATE(46)] = 1027,
  [SMALL_STATE(47)] = 1040,
  [SMALL_STATE(48)] = 1049,
  [SMALL_STATE(49)] = 1062,
  [SMALL_STATE(50)] = 1071,
  [SMALL_STATE(51)] = 1084,
  [SMALL_STATE(52)] = 1097,
  [SMALL_STATE(53)] = 1107,
  [SMALL_STATE(54)] = 1117,
  [SMALL_STATE(55)] = 1127,
  [SMALL_STATE(56)] = 1141,
  [SMALL_STATE(57)] = 1153,
  [SMALL_STATE(58)] = 1161,
  [SMALL_STATE(59)] = 1169,
  [SMALL_STATE(60)] = 1177,
  [SMALL_STATE(61)] = 1184,
  [SMALL_STATE(62)] = 1197,
  [SMALL_STATE(63)] = 1206,
  [SMALL_STATE(64)] = 1213,
  [SMALL_STATE(65)] = 1220,
  [SMALL_STATE(66)] = 1227,
  [SMALL_STATE(67)] = 1240,
  [SMALL_STATE(68)] = 1251,
  [SMALL_STATE(69)] = 1257,
  [SMALL_STATE(70)] = 1263,
  [SMALL_STATE(71)] = 1269,
  [SMALL_STATE(72)] = 1279,
  [SMALL_STATE(73)] = 1285,
  [SMALL_STATE(74)] = 1292,
  [SMALL_STATE(75)] = 1299,
  [SMALL_STATE(76)] = 1306,
  [SMALL_STATE(77)] = 1313,
  [SMALL_STATE(78)] = 1320,
  [SMALL_STATE(79)] = 1325,
  [SMALL_STATE(80)] = 1332,
  [SMALL_STATE(81)] = 1339,
  [SMALL_STATE(82)] = 1344,
  [SMALL_STATE(83)] = 1351,
  [SMALL_STATE(84)] = 1358,
  [SMALL_STATE(85)] = 1365,
  [SMALL_STATE(86)] = 1372,
  [SMALL_STATE(87)] = 1379,
  [SMALL_STATE(88)] = 1386,
  [SMALL_STATE(89)] = 1393,
  [SMALL_STATE(90)] = 1400,
  [SMALL_STATE(91)] = 1407,
  [SMALL_STATE(92)] = 1411,
  [SMALL_STATE(93)] = 1415,
  [SMALL_STATE(94)] = 1419,
  [SMALL_STATE(95)] = 1423,
  [SMALL_STATE(96)] = 1427,
  [SMALL_STATE(97)] = 1431,
  [SMALL_STATE(98)] = 1435,
  [SMALL_STATE(99)] = 1439,
  [SMALL_STATE(100)] = 1443,
  [SMALL_STATE(101)] = 1447,
  [SMALL_STATE(102)] = 1451,
  [SMALL_STATE(103)] = 1455,
  [SMALL_STATE(104)] = 1459,
  [SMALL_STATE(105)] = 1463,
  [SMALL_STATE(106)] = 1467,
  [SMALL_STATE(107)] = 1471,
  [SMALL_STATE(108)] = 1475,
  [SMALL_STATE(109)] = 1479,
  [SMALL_STATE(110)] = 1483,
  [SMALL_STATE(111)] = 1487,
  [SMALL_STATE(112)] = 1491,
  [SMALL_STATE(113)] = 1495,
  [SMALL_STATE(114)] = 1499,
  [SMALL_STATE(115)] = 1503,
  [SMALL_STATE(116)] = 1507,
  [SMALL_STATE(117)] = 1511,
  [SMALL_STATE(118)] = 1515,
  [SMALL_STATE(119)] = 1519,
  [SMALL_STATE(120)] = 1523,
  [SMALL_STATE(121)] = 1527,
  [SMALL_STATE(122)] = 1531,
  [SMALL_STATE(123)] = 1535,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_expr, 4),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scoped_expr, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_expr, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scoped_expr, 3),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(119),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(114),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(108),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__alge_expr, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(102),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(74),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(59),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(94),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(23),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_scoped_expr_repeat1, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scoped_expr_repeat1, 2),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scoped_expr_repeat1, 2), SHIFT_REPEAT(74),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_stmt, 5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_stmt, 5),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sub_alge_expr, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_access, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_iter, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__alge_list, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 4),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_definition, 5),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alge_definition, 4),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_definition, 4),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_prim, 5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_prim, 5),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_prim, 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_prim, 3),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_stmt, 4),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_stmt, 4),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_expr, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignee, 3),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignee, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optree, 5),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_identifier, 1),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optree, 6),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optree, 7),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 1),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mat, 4),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_identifier, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vec, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__param_iter, 1),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident_iter, 1),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prim_list, 1),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident_iter, 3),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_iter, 3),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [300] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__param_iter, 3),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__alge_list, 3),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prim_list, 3),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_list, 3),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vola(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
