#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 115
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 74
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_prim = 2,
  anon_sym_op = 3,
  anon_sym_field = 4,
  anon_sym_LT = 5,
  anon_sym_GT = 6,
  anon_sym_COMMA = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_COLON = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_EQ = 13,
  anon_sym_SEMI = 14,
  anon_sym_let = 15,
  anon_sym_DASH = 16,
  anon_sym_BANG = 17,
  anon_sym_SLASH = 18,
  anon_sym_STAR = 19,
  anon_sym_PLUS = 20,
  anon_sym_PLUS_EQ = 21,
  anon_sym_DASH_EQ = 22,
  anon_sym_STAR_EQ = 23,
  anon_sym_SLASH_EQ = 24,
  anon_sym_DOT = 25,
  anon_sym_LBRACK = 26,
  anon_sym_RBRACK = 27,
  anon_sym_s = 28,
  anon_sym_vec = 29,
  anon_sym_mat = 30,
  anon_sym_x = 31,
  sym_number = 32,
  sym_kw_at = 33,
  sym_kw_prim = 34,
  sym_comment = 35,
  sym_source_file = 36,
  sym__definition = 37,
  sym_prim_definition = 38,
  sym_op_definition = 39,
  sym_field_definition = 40,
  sym_prim_list = 41,
  sym__ident_iter = 42,
  sym_parameter_list = 43,
  sym__param_iter = 44,
  sym_typed_identifier = 45,
  sym_block = 46,
  sym__stmt = 47,
  sym_prim_expr = 48,
  sym_optree = 49,
  sym__prim_list = 50,
  sym_def_prim = 51,
  sym_let_stmt = 52,
  sym__art_expr = 53,
  sym__sub_art_expr = 54,
  sym_scoped_expr = 55,
  sym_unary_expr = 56,
  sym_binary_expr = 57,
  sym_assignment_stmt = 58,
  sym_assignee = 59,
  sym_call_expr = 60,
  sym__art_list = 61,
  sym_arg_access = 62,
  sym_list = 63,
  sym__list_iter = 64,
  sym__list_item = 65,
  sym__type = 66,
  sym_scalar = 67,
  sym_vec = 68,
  sym_mat = 69,
  sym_float = 70,
  aux_sym_source_file_repeat1 = 71,
  aux_sym_block_repeat1 = 72,
  aux_sym_scoped_expr_repeat1 = 73,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_prim] = "prim",
  [anon_sym_op] = "op",
  [anon_sym_field] = "field",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_s] = "s",
  [anon_sym_vec] = "vec",
  [anon_sym_mat] = "mat",
  [anon_sym_x] = "x",
  [sym_number] = "number",
  [sym_kw_at] = "kw_at",
  [sym_kw_prim] = "kw_prim",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_prim_definition] = "prim_definition",
  [sym_op_definition] = "op_definition",
  [sym_field_definition] = "field_definition",
  [sym_prim_list] = "prim_list",
  [sym__ident_iter] = "_ident_iter",
  [sym_parameter_list] = "parameter_list",
  [sym__param_iter] = "_param_iter",
  [sym_typed_identifier] = "typed_identifier",
  [sym_block] = "block",
  [sym__stmt] = "_stmt",
  [sym_prim_expr] = "prim_expr",
  [sym_optree] = "optree",
  [sym__prim_list] = "_prim_list",
  [sym_def_prim] = "def_prim",
  [sym_let_stmt] = "let_stmt",
  [sym__art_expr] = "_art_expr",
  [sym__sub_art_expr] = "_sub_art_expr",
  [sym_scoped_expr] = "scoped_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_assignment_stmt] = "assignment_stmt",
  [sym_assignee] = "assignee",
  [sym_call_expr] = "call_expr",
  [sym__art_list] = "_art_list",
  [sym_arg_access] = "arg_access",
  [sym_list] = "list",
  [sym__list_iter] = "_list_iter",
  [sym__list_item] = "_list_item",
  [sym__type] = "_type",
  [sym_scalar] = "scalar",
  [sym_vec] = "vec",
  [sym_mat] = "mat",
  [sym_float] = "float",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_scoped_expr_repeat1] = "scoped_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_prim] = anon_sym_prim,
  [anon_sym_op] = anon_sym_op,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_vec] = anon_sym_vec,
  [anon_sym_mat] = anon_sym_mat,
  [anon_sym_x] = anon_sym_x,
  [sym_number] = sym_number,
  [sym_kw_at] = sym_kw_at,
  [sym_kw_prim] = sym_kw_prim,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_prim_definition] = sym_prim_definition,
  [sym_op_definition] = sym_op_definition,
  [sym_field_definition] = sym_field_definition,
  [sym_prim_list] = sym_prim_list,
  [sym__ident_iter] = sym__ident_iter,
  [sym_parameter_list] = sym_parameter_list,
  [sym__param_iter] = sym__param_iter,
  [sym_typed_identifier] = sym_typed_identifier,
  [sym_block] = sym_block,
  [sym__stmt] = sym__stmt,
  [sym_prim_expr] = sym_prim_expr,
  [sym_optree] = sym_optree,
  [sym__prim_list] = sym__prim_list,
  [sym_def_prim] = sym_def_prim,
  [sym_let_stmt] = sym_let_stmt,
  [sym__art_expr] = sym__art_expr,
  [sym__sub_art_expr] = sym__sub_art_expr,
  [sym_scoped_expr] = sym_scoped_expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_assignment_stmt] = sym_assignment_stmt,
  [sym_assignee] = sym_assignee,
  [sym_call_expr] = sym_call_expr,
  [sym__art_list] = sym__art_list,
  [sym_arg_access] = sym_arg_access,
  [sym_list] = sym_list,
  [sym__list_iter] = sym__list_iter,
  [sym__list_item] = sym__list_item,
  [sym__type] = sym__type,
  [sym_scalar] = sym_scalar,
  [sym_vec] = sym_vec,
  [sym_mat] = sym_mat,
  [sym_float] = sym_float,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_scoped_expr_repeat1] = aux_sym_scoped_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_prim] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_op] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_at] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_prim] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_op_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_prim_list] = {
    .visible = true,
    .named = true,
  },
  [sym__ident_iter] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym__param_iter] = {
    .visible = false,
    .named = true,
  },
  [sym_typed_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_optree] = {
    .visible = true,
    .named = true,
  },
  [sym__prim_list] = {
    .visible = false,
    .named = true,
  },
  [sym_def_prim] = {
    .visible = true,
    .named = true,
  },
  [sym_let_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym__art_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__sub_art_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_scoped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_assignee] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__art_list] = {
    .visible = false,
    .named = true,
  },
  [sym_arg_access] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__list_iter] = {
    .visible = false,
    .named = true,
  },
  [sym__list_item] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_vec] = {
    .visible = true,
    .named = true,
  },
  [sym_mat] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scoped_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '+') ADVANCE(5);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_kw_at);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'm') ADVANCE(4);
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == 'p') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      if (lookahead == 'v') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_op);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_kw_prim);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_mat);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_vec);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_prim);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_prim] = ACTIONS(1),
    [anon_sym_op] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_vec] = ACTIONS(1),
    [anon_sym_mat] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_kw_at] = ACTIONS(1),
    [sym_kw_prim] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(110),
    [sym__definition] = STATE(18),
    [sym_prim_definition] = STATE(18),
    [sym_op_definition] = STATE(18),
    [sym_field_definition] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_prim] = ACTIONS(5),
    [anon_sym_op] = ACTIONS(7),
    [anon_sym_field] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(3), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    STATE(52), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [41] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(29), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(15), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    STATE(48), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [82] = 10,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 1,
      sym_kw_at,
    STATE(106), 1,
      sym__art_list,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [122] = 9,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(35), 1,
      sym_kw_at,
    STATE(111), 1,
      sym__art_list,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [159] = 9,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(35), 1,
      sym_kw_at,
    STATE(107), 1,
      sym__art_list,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [196] = 8,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(40), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [230] = 8,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(39), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [264] = 8,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(41), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [298] = 8,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(34), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [332] = 8,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(35), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [366] = 8,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(47), 1,
      sym_kw_at,
    ACTIONS(21), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(42), 9,
      sym__art_expr,
      sym__sub_art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_arg_access,
      sym_list,
      sym_float,
  [400] = 9,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym_kw_at,
    ACTIONS(53), 1,
      sym_kw_prim,
    ACTIONS(55), 1,
      sym_comment,
    STATE(39), 1,
      sym_assignee,
    STATE(105), 1,
      sym_prim_expr,
    STATE(62), 2,
      sym_optree,
      sym_call_expr,
    STATE(16), 5,
      sym__stmt,
      sym_def_prim,
      sym_let_stmt,
      sym_assignment_stmt,
      aux_sym_block_repeat1,
  [433] = 9,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym_kw_at,
    ACTIONS(53), 1,
      sym_kw_prim,
    ACTIONS(57), 1,
      sym_comment,
    STATE(39), 1,
      sym_assignee,
    STATE(100), 1,
      sym_prim_expr,
    STATE(62), 2,
      sym_optree,
      sym_call_expr,
    STATE(13), 5,
      sym__stmt,
      sym_def_prim,
      sym_let_stmt,
      sym_assignment_stmt,
      aux_sym_block_repeat1,
  [466] = 4,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_let,
    STATE(15), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    ACTIONS(61), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LBRACK,
      sym_number,
      sym_kw_at,
  [486] = 7,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      sym_kw_at,
    ACTIONS(75), 1,
      sym_kw_prim,
    ACTIONS(78), 1,
      sym_comment,
    STATE(39), 1,
      sym_assignee,
    STATE(16), 5,
      sym__stmt,
      sym_def_prim,
      sym_let_stmt,
      sym_assignment_stmt,
      aux_sym_block_repeat1,
  [512] = 2,
    ACTIONS(81), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
    ACTIONS(83), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LBRACK,
      sym_number,
      sym_kw_at,
      sym_comment,
  [528] = 6,
    ACTIONS(5), 1,
      anon_sym_prim,
    ACTIONS(7), 1,
      anon_sym_op,
    ACTIONS(9), 1,
      anon_sym_field,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 1,
      sym_comment,
    STATE(21), 5,
      sym__definition,
      sym_prim_definition,
      sym_op_definition,
      sym_field_definition,
      aux_sym_source_file_repeat1,
  [551] = 3,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(89), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [568] = 2,
    ACTIONS(97), 1,
      anon_sym_DOT,
    ACTIONS(95), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [583] = 6,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_prim,
    ACTIONS(104), 1,
      anon_sym_op,
    ACTIONS(107), 1,
      anon_sym_field,
    ACTIONS(110), 1,
      sym_comment,
    STATE(21), 5,
      sym__definition,
      sym_prim_definition,
      sym_op_definition,
      sym_field_definition,
      aux_sym_source_file_repeat1,
  [606] = 6,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    ACTIONS(115), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      sym__list_iter,
    ACTIONS(113), 2,
      sym_identifier,
      sym_kw_at,
    STATE(84), 3,
      sym_list,
      sym__list_item,
      sym_float,
  [628] = 1,
    ACTIONS(117), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [640] = 1,
    ACTIONS(119), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [652] = 1,
    ACTIONS(121), 9,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [664] = 1,
    ACTIONS(123), 9,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [676] = 1,
    ACTIONS(125), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [688] = 1,
    ACTIONS(127), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [699] = 1,
    ACTIONS(129), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [710] = 1,
    ACTIONS(131), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [721] = 1,
    ACTIONS(133), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [732] = 1,
    ACTIONS(135), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [743] = 5,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_number,
    STATE(113), 1,
      sym__list_iter,
    ACTIONS(113), 2,
      sym_identifier,
      sym_kw_at,
    STATE(84), 3,
      sym_list,
      sym__list_item,
      sym_float,
  [762] = 2,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(137), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
  [775] = 1,
    ACTIONS(137), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [786] = 4,
    ACTIONS(141), 1,
      anon_sym_s,
    ACTIONS(143), 1,
      anon_sym_vec,
    ACTIONS(145), 1,
      anon_sym_mat,
    STATE(64), 4,
      sym__type,
      sym_scalar,
      sym_vec,
      sym_mat,
  [802] = 4,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(151), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [817] = 1,
    ACTIONS(153), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [825] = 1,
    ACTIONS(155), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [833] = 3,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(151), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [845] = 4,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(77), 1,
      sym_prim_expr,
    STATE(97), 1,
      sym__prim_list,
    STATE(62), 2,
      sym_optree,
      sym_call_expr,
  [859] = 3,
    ACTIONS(161), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(151), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [871] = 1,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [879] = 3,
    ACTIONS(165), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(151), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [891] = 2,
    ACTIONS(169), 2,
      sym_kw_at,
      sym_comment,
    ACTIONS(167), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [901] = 4,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(77), 1,
      sym_prim_expr,
    STATE(88), 1,
      sym__prim_list,
    STATE(62), 2,
      sym_optree,
      sym_call_expr,
  [915] = 2,
    ACTIONS(173), 2,
      sym_kw_at,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [925] = 3,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(151), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [937] = 1,
    ACTIONS(177), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [945] = 1,
    ACTIONS(179), 5,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [953] = 1,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [961] = 3,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(151), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [973] = 3,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 1,
      anon_sym_LT,
    ACTIONS(187), 3,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [985] = 1,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [993] = 1,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
      sym_comment,
  [1001] = 2,
    ACTIONS(195), 2,
      sym_kw_at,
      sym_comment,
    ACTIONS(193), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [1011] = 4,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 1,
      anon_sym_LT,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    ACTIONS(197), 1,
      anon_sym_DOT,
  [1024] = 1,
    ACTIONS(199), 4,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1031] = 2,
    ACTIONS(203), 1,
      anon_sym_COLON,
    ACTIONS(201), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1040] = 3,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(93), 1,
      sym_prim_expr,
    STATE(62), 2,
      sym_optree,
      sym_call_expr,
  [1051] = 4,
    ACTIONS(205), 1,
      sym_identifier,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      sym_typed_identifier,
    STATE(86), 1,
      sym__param_iter,
  [1064] = 1,
    ACTIONS(187), 4,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1071] = 1,
    ACTIONS(209), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1077] = 1,
    ACTIONS(211), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1083] = 1,
    ACTIONS(213), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1089] = 3,
    ACTIONS(205), 1,
      sym_identifier,
    STATE(75), 1,
      sym_typed_identifier,
    STATE(103), 1,
      sym__param_iter,
  [1099] = 1,
    ACTIONS(215), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1105] = 2,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_block,
  [1112] = 2,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_block,
  [1119] = 2,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(96), 1,
      sym__ident_iter,
  [1126] = 2,
    ACTIONS(221), 1,
      anon_sym_EQ,
    ACTIONS(223), 1,
      anon_sym_SEMI,
  [1133] = 1,
    ACTIONS(225), 2,
      sym_identifier,
      sym_kw_at,
  [1138] = 2,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    STATE(79), 1,
      sym_parameter_list,
  [1145] = 1,
    ACTIONS(229), 2,
      sym_identifier,
      sym_kw_at,
  [1150] = 2,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
  [1157] = 2,
    ACTIONS(235), 1,
      anon_sym_GT,
    ACTIONS(237), 1,
      anon_sym_COMMA,
  [1164] = 2,
    ACTIONS(239), 1,
      anon_sym_GT,
    ACTIONS(241), 1,
      anon_sym_COMMA,
  [1171] = 2,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym_parameter_list,
  [1178] = 2,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_block,
  [1185] = 2,
    ACTIONS(243), 1,
      anon_sym_LT,
    STATE(73), 1,
      sym_prim_list,
  [1192] = 2,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    STATE(69), 1,
      sym_parameter_list,
  [1199] = 2,
    ACTIONS(205), 1,
      sym_identifier,
    STATE(104), 1,
      sym_typed_identifier,
  [1206] = 2,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(108), 1,
      sym__ident_iter,
  [1213] = 2,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_RBRACK,
  [1220] = 1,
    ACTIONS(249), 1,
      sym_number,
  [1224] = 1,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
  [1228] = 1,
    ACTIONS(253), 1,
      anon_sym_RBRACK,
  [1232] = 1,
    ACTIONS(255), 1,
      anon_sym_GT,
  [1236] = 1,
    ACTIONS(257), 1,
      sym_identifier,
  [1240] = 1,
    ACTIONS(259), 1,
      sym_identifier,
  [1244] = 1,
    ACTIONS(261), 1,
      anon_sym_LPAREN,
  [1248] = 1,
    ACTIONS(263), 1,
      anon_sym_LBRACE,
  [1252] = 1,
    ACTIONS(265), 1,
      anon_sym_SEMI,
  [1256] = 1,
    ACTIONS(267), 1,
      sym_number,
  [1260] = 1,
    ACTIONS(269), 1,
      anon_sym_LPAREN,
  [1264] = 1,
    ACTIONS(271), 1,
      anon_sym_GT,
  [1268] = 1,
    ACTIONS(273), 1,
      anon_sym_GT,
  [1272] = 1,
    ACTIONS(275), 1,
      sym_number,
  [1276] = 1,
    ACTIONS(277), 1,
      sym_number,
  [1280] = 1,
    ACTIONS(279), 1,
      anon_sym_RBRACE,
  [1284] = 1,
    ACTIONS(281), 1,
      anon_sym_LBRACE,
  [1288] = 1,
    ACTIONS(197), 1,
      anon_sym_DOT,
  [1292] = 1,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
  [1296] = 1,
    ACTIONS(285), 1,
      anon_sym_EQ,
  [1300] = 1,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
  [1304] = 1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [1308] = 1,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [1312] = 1,
    ACTIONS(293), 1,
      anon_sym_GT,
  [1316] = 1,
    ACTIONS(295), 1,
      anon_sym_x,
  [1320] = 1,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
  [1324] = 1,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
  [1328] = 1,
    ACTIONS(301), 1,
      sym_identifier,
  [1332] = 1,
    ACTIONS(303), 1,
      anon_sym_RBRACK,
  [1336] = 1,
    ACTIONS(305), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 122,
  [SMALL_STATE(6)] = 159,
  [SMALL_STATE(7)] = 196,
  [SMALL_STATE(8)] = 230,
  [SMALL_STATE(9)] = 264,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 332,
  [SMALL_STATE(12)] = 366,
  [SMALL_STATE(13)] = 400,
  [SMALL_STATE(14)] = 433,
  [SMALL_STATE(15)] = 466,
  [SMALL_STATE(16)] = 486,
  [SMALL_STATE(17)] = 512,
  [SMALL_STATE(18)] = 528,
  [SMALL_STATE(19)] = 551,
  [SMALL_STATE(20)] = 568,
  [SMALL_STATE(21)] = 583,
  [SMALL_STATE(22)] = 606,
  [SMALL_STATE(23)] = 628,
  [SMALL_STATE(24)] = 640,
  [SMALL_STATE(25)] = 652,
  [SMALL_STATE(26)] = 664,
  [SMALL_STATE(27)] = 676,
  [SMALL_STATE(28)] = 688,
  [SMALL_STATE(29)] = 699,
  [SMALL_STATE(30)] = 710,
  [SMALL_STATE(31)] = 721,
  [SMALL_STATE(32)] = 732,
  [SMALL_STATE(33)] = 743,
  [SMALL_STATE(34)] = 762,
  [SMALL_STATE(35)] = 775,
  [SMALL_STATE(36)] = 786,
  [SMALL_STATE(37)] = 802,
  [SMALL_STATE(38)] = 817,
  [SMALL_STATE(39)] = 825,
  [SMALL_STATE(40)] = 833,
  [SMALL_STATE(41)] = 845,
  [SMALL_STATE(42)] = 859,
  [SMALL_STATE(43)] = 871,
  [SMALL_STATE(44)] = 879,
  [SMALL_STATE(45)] = 891,
  [SMALL_STATE(46)] = 901,
  [SMALL_STATE(47)] = 915,
  [SMALL_STATE(48)] = 925,
  [SMALL_STATE(49)] = 937,
  [SMALL_STATE(50)] = 945,
  [SMALL_STATE(51)] = 953,
  [SMALL_STATE(52)] = 961,
  [SMALL_STATE(53)] = 973,
  [SMALL_STATE(54)] = 985,
  [SMALL_STATE(55)] = 993,
  [SMALL_STATE(56)] = 1001,
  [SMALL_STATE(57)] = 1011,
  [SMALL_STATE(58)] = 1024,
  [SMALL_STATE(59)] = 1031,
  [SMALL_STATE(60)] = 1040,
  [SMALL_STATE(61)] = 1051,
  [SMALL_STATE(62)] = 1064,
  [SMALL_STATE(63)] = 1071,
  [SMALL_STATE(64)] = 1077,
  [SMALL_STATE(65)] = 1083,
  [SMALL_STATE(66)] = 1089,
  [SMALL_STATE(67)] = 1099,
  [SMALL_STATE(68)] = 1105,
  [SMALL_STATE(69)] = 1112,
  [SMALL_STATE(70)] = 1119,
  [SMALL_STATE(71)] = 1126,
  [SMALL_STATE(72)] = 1133,
  [SMALL_STATE(73)] = 1138,
  [SMALL_STATE(74)] = 1145,
  [SMALL_STATE(75)] = 1150,
  [SMALL_STATE(76)] = 1157,
  [SMALL_STATE(77)] = 1164,
  [SMALL_STATE(78)] = 1171,
  [SMALL_STATE(79)] = 1178,
  [SMALL_STATE(80)] = 1185,
  [SMALL_STATE(81)] = 1192,
  [SMALL_STATE(82)] = 1199,
  [SMALL_STATE(83)] = 1206,
  [SMALL_STATE(84)] = 1213,
  [SMALL_STATE(85)] = 1220,
  [SMALL_STATE(86)] = 1224,
  [SMALL_STATE(87)] = 1228,
  [SMALL_STATE(88)] = 1232,
  [SMALL_STATE(89)] = 1236,
  [SMALL_STATE(90)] = 1240,
  [SMALL_STATE(91)] = 1244,
  [SMALL_STATE(92)] = 1248,
  [SMALL_STATE(93)] = 1252,
  [SMALL_STATE(94)] = 1256,
  [SMALL_STATE(95)] = 1260,
  [SMALL_STATE(96)] = 1264,
  [SMALL_STATE(97)] = 1268,
  [SMALL_STATE(98)] = 1272,
  [SMALL_STATE(99)] = 1276,
  [SMALL_STATE(100)] = 1280,
  [SMALL_STATE(101)] = 1284,
  [SMALL_STATE(102)] = 1288,
  [SMALL_STATE(103)] = 1292,
  [SMALL_STATE(104)] = 1296,
  [SMALL_STATE(105)] = 1300,
  [SMALL_STATE(106)] = 1304,
  [SMALL_STATE(107)] = 1308,
  [SMALL_STATE(108)] = 1312,
  [SMALL_STATE(109)] = 1316,
  [SMALL_STATE(110)] = 1320,
  [SMALL_STATE(111)] = 1324,
  [SMALL_STATE(112)] = 1328,
  [SMALL_STATE(113)] = 1332,
  [SMALL_STATE(114)] = 1336,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_scoped_expr_repeat1, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scoped_expr_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scoped_expr_repeat1, 2), SHIFT_REPEAT(82),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(102),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(82),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(38),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(89),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(16),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_stmt, 5),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_stmt, 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__art_expr, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(90),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(114),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(112),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_access, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_expr, 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sub_art_expr, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_expr, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__art_list, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignee, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_prim, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_prim, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_prim, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_prim, 5),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignee, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_definition, 5),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_expr, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_definition, 4),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 4),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_stmt, 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_stmt, 4),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optree, 7),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_identifier, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vec, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_identifier, 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mat, 4),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__param_iter, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident_iter, 1),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prim_list, 1),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_iter, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_list, 3),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prim_list, 3),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__param_iter, 3),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__art_list, 3),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident_iter, 3),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [297] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_iter, 3),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vola(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
