#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_prim = 2,
  anon_sym_op = 3,
  anon_sym_field = 4,
  anon_sym_LT = 5,
  anon_sym_GT = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_COLON = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_COMMA = 12,
  anon_sym_EQ = 13,
  anon_sym_SEMI = 14,
  anon_sym_DOT = 15,
  anon_sym_let = 16,
  anon_sym_DASH = 17,
  anon_sym_BANG = 18,
  anon_sym_SLASH = 19,
  anon_sym_STAR = 20,
  anon_sym_PLUS = 21,
  anon_sym_LBRACK = 22,
  anon_sym_RBRACK = 23,
  anon_sym_s = 24,
  anon_sym_vec = 25,
  anon_sym_mat = 26,
  anon_sym_x = 27,
  sym_number = 28,
  sym_kw_at = 29,
  sym_kw_prim = 30,
  sym_source_file = 31,
  sym__definition = 32,
  sym_prim_definition = 33,
  sym_op_definition = 34,
  sym_field_definition = 35,
  sym_prim_list = 36,
  sym_parameter_list = 37,
  sym_typed_identifier = 38,
  sym_block = 39,
  sym__stmt = 40,
  sym_prim_expr = 41,
  sym_optree = 42,
  sym__prim_list = 43,
  sym_def_prim = 44,
  sym_set_prim = 45,
  sym_set_at = 46,
  sym_let_stmt = 47,
  sym__art_expr = 48,
  sym_scoped_expr = 49,
  sym_unary_expr = 50,
  sym_binary_expr = 51,
  sym_call_expr = 52,
  sym__art_list = 53,
  sym_list = 54,
  sym__list_iter = 55,
  sym__list_item = 56,
  sym__type = 57,
  sym_scalar = 58,
  sym_vec = 59,
  sym_mat = 60,
  sym_float = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym_prim_list_repeat1 = 63,
  aux_sym_parameter_list_repeat1 = 64,
  aux_sym_block_repeat1 = 65,
  aux_sym_scoped_expr_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_prim] = "prim",
  [anon_sym_op] = "op",
  [anon_sym_field] = "field",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_let] = "let",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_s] = "s",
  [anon_sym_vec] = "vec",
  [anon_sym_mat] = "mat",
  [anon_sym_x] = "x",
  [sym_number] = "number",
  [sym_kw_at] = "kw_at",
  [sym_kw_prim] = "kw_prim",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_prim_definition] = "prim_definition",
  [sym_op_definition] = "op_definition",
  [sym_field_definition] = "field_definition",
  [sym_prim_list] = "prim_list",
  [sym_parameter_list] = "parameter_list",
  [sym_typed_identifier] = "typed_identifier",
  [sym_block] = "block",
  [sym__stmt] = "_stmt",
  [sym_prim_expr] = "prim_expr",
  [sym_optree] = "optree",
  [sym__prim_list] = "_prim_list",
  [sym_def_prim] = "def_prim",
  [sym_set_prim] = "set_prim",
  [sym_set_at] = "set_at",
  [sym_let_stmt] = "let_stmt",
  [sym__art_expr] = "_art_expr",
  [sym_scoped_expr] = "scoped_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_call_expr] = "call_expr",
  [sym__art_list] = "_art_list",
  [sym_list] = "list",
  [sym__list_iter] = "_list_iter",
  [sym__list_item] = "_list_item",
  [sym__type] = "_type",
  [sym_scalar] = "scalar",
  [sym_vec] = "vec",
  [sym_mat] = "mat",
  [sym_float] = "float",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_prim_list_repeat1] = "prim_list_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_scoped_expr_repeat1] = "scoped_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_prim] = anon_sym_prim,
  [anon_sym_op] = anon_sym_op,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_vec] = anon_sym_vec,
  [anon_sym_mat] = anon_sym_mat,
  [anon_sym_x] = anon_sym_x,
  [sym_number] = sym_number,
  [sym_kw_at] = sym_kw_at,
  [sym_kw_prim] = sym_kw_prim,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_prim_definition] = sym_prim_definition,
  [sym_op_definition] = sym_op_definition,
  [sym_field_definition] = sym_field_definition,
  [sym_prim_list] = sym_prim_list,
  [sym_parameter_list] = sym_parameter_list,
  [sym_typed_identifier] = sym_typed_identifier,
  [sym_block] = sym_block,
  [sym__stmt] = sym__stmt,
  [sym_prim_expr] = sym_prim_expr,
  [sym_optree] = sym_optree,
  [sym__prim_list] = sym__prim_list,
  [sym_def_prim] = sym_def_prim,
  [sym_set_prim] = sym_set_prim,
  [sym_set_at] = sym_set_at,
  [sym_let_stmt] = sym_let_stmt,
  [sym__art_expr] = sym__art_expr,
  [sym_scoped_expr] = sym_scoped_expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_call_expr] = sym_call_expr,
  [sym__art_list] = sym__art_list,
  [sym_list] = sym_list,
  [sym__list_iter] = sym__list_iter,
  [sym__list_item] = sym__list_item,
  [sym__type] = sym__type,
  [sym_scalar] = sym_scalar,
  [sym_vec] = sym_vec,
  [sym_mat] = sym_mat,
  [sym_float] = sym_float,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_prim_list_repeat1] = aux_sym_prim_list_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_scoped_expr_repeat1] = aux_sym_scoped_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_prim] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_op] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_at] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_prim] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_op_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_prim_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_typed_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_optree] = {
    .visible = true,
    .named = true,
  },
  [sym__prim_list] = {
    .visible = false,
    .named = true,
  },
  [sym_def_prim] = {
    .visible = true,
    .named = true,
  },
  [sym_set_prim] = {
    .visible = true,
    .named = true,
  },
  [sym_set_at] = {
    .visible = true,
    .named = true,
  },
  [sym_let_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym__art_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_scoped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__art_list] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__list_iter] = {
    .visible = false,
    .named = true,
  },
  [sym__list_item] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_vec] = {
    .visible = true,
    .named = true,
  },
  [sym_mat] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prim_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scoped_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '!') ADVANCE(14);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ')') ADVANCE(5);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(9);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '<') ADVANCE(2);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '>') ADVANCE(3);
      if (lookahead == '@') ADVANCE(22);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_kw_at);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'm') ADVANCE(4);
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == 'p') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      if (lookahead == 'v') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_op);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_kw_prim);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_mat);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_vec);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_prim);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_prim] = ACTIONS(1),
    [anon_sym_op] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_vec] = ACTIONS(1),
    [anon_sym_mat] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_kw_at] = ACTIONS(1),
    [sym_kw_prim] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(107),
    [sym__definition] = STATE(23),
    [sym_prim_definition] = STATE(23),
    [sym_op_definition] = STATE(23),
    [sym_field_definition] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_prim] = ACTIONS(5),
    [anon_sym_op] = ACTIONS(7),
    [anon_sym_field] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(3), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    STATE(38), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [36] = 9,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(18), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    STATE(41), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [72] = 9,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    ACTIONS(31), 1,
      sym_kw_at,
    STATE(98), 1,
      sym__art_list,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [107] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_kw_at,
    STATE(100), 1,
      sym__art_list,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [139] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_kw_at,
    STATE(106), 1,
      sym__art_list,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [171] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(39), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [200] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(35), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [229] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [258] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(39), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(30), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [287] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(41), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(40), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [316] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(33), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [345] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_kw_at,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(43), 7,
      sym__art_expr,
      sym_scoped_expr,
      sym_unary_expr,
      sym_binary_expr,
      sym_call_expr,
      sym_list,
      sym_float,
  [374] = 7,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(49), 1,
      sym_kw_at,
    ACTIONS(51), 1,
      sym_kw_prim,
    STATE(90), 1,
      sym_prim_expr,
    STATE(60), 2,
      sym_optree,
      sym_call_expr,
    STATE(15), 6,
      sym__stmt,
      sym_def_prim,
      sym_set_prim,
      sym_set_at,
      sym_let_stmt,
      aux_sym_block_repeat1,
  [402] = 7,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(49), 1,
      sym_kw_at,
    ACTIONS(51), 1,
      sym_kw_prim,
    STATE(96), 1,
      sym_prim_expr,
    STATE(60), 2,
      sym_optree,
      sym_call_expr,
    STATE(17), 6,
      sym__stmt,
      sym_def_prim,
      sym_set_prim,
      sym_set_at,
      sym_let_stmt,
      aux_sym_block_repeat1,
  [430] = 2,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(53), 9,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [445] = 5,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(60), 1,
      anon_sym_let,
    ACTIONS(63), 1,
      sym_kw_at,
    ACTIONS(66), 1,
      sym_kw_prim,
    STATE(17), 6,
      sym__stmt,
      sym_def_prim,
      sym_set_prim,
      sym_set_at,
      sym_let_stmt,
      aux_sym_block_repeat1,
  [466] = 4,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_let,
    STATE(18), 2,
      sym_let_stmt,
      aux_sym_scoped_expr_repeat1,
    ACTIONS(71), 6,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LBRACK,
      sym_number,
      sym_kw_at,
  [485] = 1,
    ACTIONS(76), 9,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [497] = 2,
    ACTIONS(78), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
    ACTIONS(80), 6,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LBRACK,
      sym_number,
      sym_kw_at,
  [511] = 2,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 8,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [525] = 6,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(88), 1,
      anon_sym_RBRACK,
    STATE(99), 1,
      sym__list_iter,
    ACTIONS(86), 2,
      sym_identifier,
      sym_kw_at,
    STATE(80), 3,
      sym_list,
      sym__list_item,
      sym_float,
  [547] = 5,
    ACTIONS(5), 1,
      anon_sym_prim,
    ACTIONS(7), 1,
      anon_sym_op,
    ACTIONS(9), 1,
      anon_sym_field,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    STATE(25), 5,
      sym__definition,
      sym_prim_definition,
      sym_op_definition,
      sym_field_definition,
      aux_sym_source_file_repeat1,
  [567] = 1,
    ACTIONS(92), 9,
      anon_sym_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [579] = 5,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_prim,
    ACTIONS(99), 1,
      anon_sym_op,
    ACTIONS(102), 1,
      anon_sym_field,
    STATE(25), 5,
      sym__definition,
      sym_prim_definition,
      sym_op_definition,
      sym_field_definition,
      aux_sym_source_file_repeat1,
  [599] = 1,
    ACTIONS(105), 9,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [611] = 1,
    ACTIONS(107), 9,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACK,
  [623] = 1,
    ACTIONS(109), 9,
      anon_sym_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [635] = 5,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    STATE(108), 1,
      sym__list_iter,
    ACTIONS(86), 2,
      sym_identifier,
      sym_kw_at,
    STATE(80), 3,
      sym_list,
      sym__list_item,
      sym_float,
  [654] = 2,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(111), 6,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
  [667] = 1,
    ACTIONS(115), 8,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [678] = 1,
    ACTIONS(117), 8,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [689] = 1,
    ACTIONS(111), 8,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [700] = 1,
    ACTIONS(119), 8,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [711] = 4,
    ACTIONS(121), 1,
      anon_sym_s,
    ACTIONS(123), 1,
      anon_sym_vec,
    ACTIONS(125), 1,
      anon_sym_mat,
    STATE(68), 4,
      sym__type,
      sym_scalar,
      sym_vec,
      sym_mat,
  [727] = 4,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(131), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [742] = 3,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(131), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [754] = 3,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(131), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [766] = 3,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(131), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [778] = 3,
    ACTIONS(139), 1,
      anon_sym_SEMI,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(131), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [790] = 3,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(131), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [802] = 4,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(71), 1,
      sym_prim_expr,
    STATE(101), 1,
      sym__prim_list,
    STATE(60), 2,
      sym_optree,
      sym_call_expr,
  [816] = 3,
    ACTIONS(145), 1,
      anon_sym_SEMI,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(131), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [828] = 3,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      anon_sym_LT,
    ACTIONS(149), 3,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [840] = 4,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(71), 1,
      sym_prim_expr,
    STATE(92), 1,
      sym__prim_list,
    STATE(60), 2,
      sym_optree,
      sym_call_expr,
  [854] = 4,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      anon_sym_LT,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(151), 1,
      anon_sym_DOT,
  [867] = 3,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(47), 2,
      sym_typed_identifier,
      aux_sym_parameter_list_repeat1,
  [878] = 1,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
  [885] = 3,
    ACTIONS(160), 1,
      sym_identifier,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(59), 2,
      sym_typed_identifier,
      aux_sym_parameter_list_repeat1,
  [896] = 1,
    ACTIONS(164), 4,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
  [903] = 3,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(89), 1,
      sym_prim_expr,
    STATE(60), 2,
      sym_optree,
      sym_call_expr,
  [914] = 2,
    ACTIONS(168), 1,
      sym_kw_at,
    ACTIONS(166), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [923] = 1,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
  [930] = 2,
    ACTIONS(174), 1,
      sym_kw_at,
    ACTIONS(172), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [939] = 2,
    ACTIONS(178), 1,
      anon_sym_COLON,
    ACTIONS(176), 3,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_identifier,
  [948] = 1,
    ACTIONS(180), 4,
      anon_sym_GT,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [955] = 1,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
  [962] = 2,
    ACTIONS(186), 1,
      sym_kw_at,
    ACTIONS(184), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [971] = 3,
    ACTIONS(160), 1,
      sym_identifier,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(47), 2,
      sym_typed_identifier,
      aux_sym_parameter_list_repeat1,
  [982] = 1,
    ACTIONS(149), 4,
      anon_sym_GT,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [989] = 2,
    ACTIONS(192), 1,
      sym_kw_at,
    ACTIONS(190), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [998] = 2,
    ACTIONS(196), 1,
      sym_kw_at,
    ACTIONS(194), 3,
      anon_sym_let,
      sym_identifier,
      sym_kw_prim,
  [1007] = 1,
    ACTIONS(198), 4,
      ts_builtin_sym_end,
      anon_sym_prim,
      anon_sym_op,
      anon_sym_field,
  [1014] = 1,
    ACTIONS(200), 3,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_identifier,
  [1020] = 3,
    ACTIONS(202), 1,
      sym_identifier,
    ACTIONS(204), 1,
      anon_sym_GT,
    STATE(70), 1,
      aux_sym_prim_list_repeat1,
  [1030] = 1,
    ACTIONS(206), 3,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_identifier,
  [1036] = 2,
    ACTIONS(210), 1,
      anon_sym_EQ,
    ACTIONS(208), 2,
      sym_identifier,
      sym_kw_at,
  [1044] = 1,
    ACTIONS(212), 3,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_identifier,
  [1050] = 1,
    ACTIONS(214), 3,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_identifier,
  [1056] = 3,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(219), 1,
      anon_sym_GT,
    STATE(70), 1,
      aux_sym_prim_list_repeat1,
  [1066] = 2,
    ACTIONS(221), 1,
      anon_sym_GT,
    ACTIONS(223), 1,
      anon_sym_COMMA,
  [1073] = 2,
    ACTIONS(225), 1,
      anon_sym_EQ,
    ACTIONS(227), 1,
      anon_sym_SEMI,
  [1080] = 2,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      sym_parameter_list,
  [1087] = 2,
    ACTIONS(231), 1,
      anon_sym_LT,
    STATE(78), 1,
      sym_prim_list,
  [1094] = 2,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    STATE(79), 1,
      sym_parameter_list,
  [1101] = 2,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(63), 1,
      sym_block,
  [1108] = 2,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(65), 1,
      aux_sym_prim_list_repeat1,
  [1115] = 2,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    STATE(81), 1,
      sym_parameter_list,
  [1122] = 2,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(57), 1,
      sym_block,
  [1129] = 2,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RBRACK,
  [1136] = 2,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_block,
  [1143] = 2,
    ACTIONS(160), 1,
      sym_identifier,
    STATE(85), 1,
      sym_typed_identifier,
  [1150] = 1,
    ACTIONS(241), 1,
      sym_number,
  [1154] = 1,
    ACTIONS(243), 1,
      anon_sym_x,
  [1158] = 1,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [1162] = 1,
    ACTIONS(247), 1,
      sym_number,
  [1166] = 1,
    ACTIONS(249), 1,
      sym_number,
  [1170] = 1,
    ACTIONS(251), 1,
      anon_sym_LPAREN,
  [1174] = 1,
    ACTIONS(253), 1,
      anon_sym_SEMI,
  [1178] = 1,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
  [1182] = 1,
    ACTIONS(257), 1,
      sym_identifier,
  [1186] = 1,
    ACTIONS(259), 1,
      anon_sym_GT,
  [1190] = 1,
    ACTIONS(261), 1,
      anon_sym_EQ,
  [1194] = 1,
    ACTIONS(263), 1,
      anon_sym_EQ,
  [1198] = 1,
    ACTIONS(265), 1,
      anon_sym_LBRACE,
  [1202] = 1,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
  [1206] = 1,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
  [1210] = 1,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
  [1214] = 1,
    ACTIONS(273), 1,
      anon_sym_RBRACK,
  [1218] = 1,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
  [1222] = 1,
    ACTIONS(277), 1,
      anon_sym_GT,
  [1226] = 1,
    ACTIONS(279), 1,
      sym_identifier,
  [1230] = 1,
    ACTIONS(281), 1,
      sym_number,
  [1234] = 1,
    ACTIONS(151), 1,
      anon_sym_DOT,
  [1238] = 1,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
  [1242] = 1,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
  [1246] = 1,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
  [1250] = 1,
    ACTIONS(289), 1,
      anon_sym_RBRACK,
  [1254] = 1,
    ACTIONS(291), 1,
      sym_identifier,
  [1258] = 1,
    ACTIONS(293), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 139,
  [SMALL_STATE(7)] = 171,
  [SMALL_STATE(8)] = 200,
  [SMALL_STATE(9)] = 229,
  [SMALL_STATE(10)] = 258,
  [SMALL_STATE(11)] = 287,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 345,
  [SMALL_STATE(14)] = 374,
  [SMALL_STATE(15)] = 402,
  [SMALL_STATE(16)] = 430,
  [SMALL_STATE(17)] = 445,
  [SMALL_STATE(18)] = 466,
  [SMALL_STATE(19)] = 485,
  [SMALL_STATE(20)] = 497,
  [SMALL_STATE(21)] = 511,
  [SMALL_STATE(22)] = 525,
  [SMALL_STATE(23)] = 547,
  [SMALL_STATE(24)] = 567,
  [SMALL_STATE(25)] = 579,
  [SMALL_STATE(26)] = 599,
  [SMALL_STATE(27)] = 611,
  [SMALL_STATE(28)] = 623,
  [SMALL_STATE(29)] = 635,
  [SMALL_STATE(30)] = 654,
  [SMALL_STATE(31)] = 667,
  [SMALL_STATE(32)] = 678,
  [SMALL_STATE(33)] = 689,
  [SMALL_STATE(34)] = 700,
  [SMALL_STATE(35)] = 711,
  [SMALL_STATE(36)] = 727,
  [SMALL_STATE(37)] = 742,
  [SMALL_STATE(38)] = 754,
  [SMALL_STATE(39)] = 766,
  [SMALL_STATE(40)] = 778,
  [SMALL_STATE(41)] = 790,
  [SMALL_STATE(42)] = 802,
  [SMALL_STATE(43)] = 816,
  [SMALL_STATE(44)] = 828,
  [SMALL_STATE(45)] = 840,
  [SMALL_STATE(46)] = 854,
  [SMALL_STATE(47)] = 867,
  [SMALL_STATE(48)] = 878,
  [SMALL_STATE(49)] = 885,
  [SMALL_STATE(50)] = 896,
  [SMALL_STATE(51)] = 903,
  [SMALL_STATE(52)] = 914,
  [SMALL_STATE(53)] = 923,
  [SMALL_STATE(54)] = 930,
  [SMALL_STATE(55)] = 939,
  [SMALL_STATE(56)] = 948,
  [SMALL_STATE(57)] = 955,
  [SMALL_STATE(58)] = 962,
  [SMALL_STATE(59)] = 971,
  [SMALL_STATE(60)] = 982,
  [SMALL_STATE(61)] = 989,
  [SMALL_STATE(62)] = 998,
  [SMALL_STATE(63)] = 1007,
  [SMALL_STATE(64)] = 1014,
  [SMALL_STATE(65)] = 1020,
  [SMALL_STATE(66)] = 1030,
  [SMALL_STATE(67)] = 1036,
  [SMALL_STATE(68)] = 1044,
  [SMALL_STATE(69)] = 1050,
  [SMALL_STATE(70)] = 1056,
  [SMALL_STATE(71)] = 1066,
  [SMALL_STATE(72)] = 1073,
  [SMALL_STATE(73)] = 1080,
  [SMALL_STATE(74)] = 1087,
  [SMALL_STATE(75)] = 1094,
  [SMALL_STATE(76)] = 1101,
  [SMALL_STATE(77)] = 1108,
  [SMALL_STATE(78)] = 1115,
  [SMALL_STATE(79)] = 1122,
  [SMALL_STATE(80)] = 1129,
  [SMALL_STATE(81)] = 1136,
  [SMALL_STATE(82)] = 1143,
  [SMALL_STATE(83)] = 1150,
  [SMALL_STATE(84)] = 1154,
  [SMALL_STATE(85)] = 1158,
  [SMALL_STATE(86)] = 1162,
  [SMALL_STATE(87)] = 1166,
  [SMALL_STATE(88)] = 1170,
  [SMALL_STATE(89)] = 1174,
  [SMALL_STATE(90)] = 1178,
  [SMALL_STATE(91)] = 1182,
  [SMALL_STATE(92)] = 1186,
  [SMALL_STATE(93)] = 1190,
  [SMALL_STATE(94)] = 1194,
  [SMALL_STATE(95)] = 1198,
  [SMALL_STATE(96)] = 1202,
  [SMALL_STATE(97)] = 1206,
  [SMALL_STATE(98)] = 1210,
  [SMALL_STATE(99)] = 1214,
  [SMALL_STATE(100)] = 1218,
  [SMALL_STATE(101)] = 1222,
  [SMALL_STATE(102)] = 1226,
  [SMALL_STATE(103)] = 1230,
  [SMALL_STATE(104)] = 1234,
  [SMALL_STATE(105)] = 1238,
  [SMALL_STATE(106)] = 1242,
  [SMALL_STATE(107)] = 1246,
  [SMALL_STATE(108)] = 1250,
  [SMALL_STATE(109)] = 1254,
  [SMALL_STATE(110)] = 1258,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(104),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(82),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(93),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(91),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_scoped_expr_repeat1, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scoped_expr_repeat1, 2),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scoped_expr_repeat1, 2), SHIFT_REPEAT(82),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_stmt, 5),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_stmt, 5),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__art_expr, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(102),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(109),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 4),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_expr, 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_expr, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__art_list, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_expr, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(55),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_definition, 5),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_prim, 5),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_prim, 5),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_prim, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_prim, 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_identifier, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optree, 7),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 4),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_prim, 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_prim, 5),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_at, 4),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_at, 4),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_prim, 6),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_prim, 6),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_definition, 4),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vec, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mat, 4),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_identifier, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 1),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prim_list_repeat1, 2), SHIFT_REPEAT(70),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prim_list_repeat1, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prim_list, 1),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_iter, 1),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_list, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prim_list, 3),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__art_list, 3),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [287] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_iter, 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vola(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
