[package]
name = "rvsdg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["dot"]
dot = ["graphviz-rust"]


[dependencies]
thiserror.workspace = true
ahash.workspace = true
slotmap.workspace = true
annotate-snippets.workspace = true
graphviz-rust = {workspace = true, optional = true}
smallvec.workspace = true
