[package]
name = "rvsdg-viewer-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
rvsdg-viewer = {path = "../rvsdg-viewer", features = ["viewer"]}
macroquad.workspace = true
font-kit = "0.13.0"


[dev-dependencies]
rvsdg = {path = "../rvsdg"}
