[package]
name = "rvsdg-viewer-ui"
version = "0.2.0"
edition = "2021"

[dependencies]
rvsdg-viewer = { path = "../rvsdg-viewer", features = ["viewer"] }
rvsdg = { path = "../rvsdg" }
iced = { version = "0.12", features = ["canvas", "debug"] }
