[package]
name = "rvsdg-viewer-ui"
version = "0.2.0"
edition = "2021"

[dependencies]
rvsdg-viewer = { workspace = true, features = ["viewer"] }
rvsdg = { workspace = true, features = ["parse"] }
iced = { version = "0.13", features = ["canvas", "debug"] }
